import tkinter as tk 
from tkinter import *
from tkinter import ttk
window=tk.Tk()
window.title("T-Town Vetinary Clinic Database")

dogphoto = PhotoImage(file="dog.png")
label1=tk.Label(window,image=dogphoto)
button1=tk.Button(window,text="Search by name")
entry1=tk.Entry(window,text="")
label2=tk.Label(window,text="Client Database")
button2=tk.Button(window,text="Previous")
button3=tk.Button(window,text="Next")
button4=tk.Button(window,text="Save Entry",relief=SUNKEN)
label4=tk.Label(window,text="Name")
label5=tk.Label(window,text="Type")
label6=tk.Label(window,text="Breed")
label7=tk.Label(window,text="Owner")
label8=tk.Label(window,text="Birthdate")
entry2=tk.Entry(window,text="")
entry3=tk.Entry(window,text="")
entry4=tk.Entry(window,text="")
entry5=tk.Entry(window,text="")
entry6=tk.Entry(window,text="")

label1.grid(row=1,column=1,rowspan=2)
button1.grid(row=1,column=4)
entry1.grid(row=1,column=5)
label2.grid(row=2,column=3)
button2.grid(row=5,column=1)
button3.grid(row=5,column=5)
button4.grid(row=5,column=3)
label4.grid(row=3,column=1)
label5.grid(row=3,column=2)
label6.grid(row=3,column=3)
label7.grid(row=3,column=4)
label8.grid(row=3,column=5)
entry2.grid(row=4,column=1)
entry3.grid(row=4,column=2)
entry4.grid(row=4,column=3)
entry5.grid(row=4,column=4)
entry6.grid(row=4,column=5)

window.mainloop()
